/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPlayer, IPlayerInterface } from "../IPlayer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "device",
        type: "address",
      },
    ],
    name: "deviceToPlayer",
    outputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPlayer__factory {
  static readonly abi = _abi;
  static createInterface(): IPlayerInterface {
    return new utils.Interface(_abi) as IPlayerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPlayer {
    return new Contract(address, _abi, signerOrProvider) as IPlayer;
  }
}
