/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RubyRouter } from "./RubyRouter";
export * as factories from "./factories";
export { RubyRouter__factory } from "./factories/RubyRouter__factory";
